app/urls.py
from django.contrib import admin
from django.urls import path

from www import views

urlpatterns = [
    path('', views.index),
    path('<int:house_id>', views.detail, name='detail'),
    path('<int:house_id>/results/', views.results, name='results'),
    path('<int:house_id>/vote/', views.vote, name='vote'),
    path('admin/', admin.site.urls),
]

www/urls.py
from django.urls import path

from . import views

app_name = 'www'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:house_id>', views.detail, name='detail'),
    path('<int:house_id>/results/', views.results, name='results'),
    path('<int:house_id>/vote/', views.vote, name='vote'),
]

www/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.


# Model house
class House(models.Model):
    name_house = models.CharField(max_length=2000)
    price_house = models.FloatField(10.000000)
    pub_date = models.DateTimeField('date publish')

    def __str__(self):
        return self.name_house

    def was_published_recently_for_house_model(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# Model Flat
class Flat(models.Model):
    name_flat = models.CharField(max_length=1999)
    price_flat = models.FloatField(5.000000)
    pub_date = models.DateTimeField('date publish')

    def __str__(self):
        return self.name_flat

    def was_published_recently_for_flat_model(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# Model Land
class Land(models.Model):
    name_land = models.CharField(max_length=1000)
    price_land = models.FloatField(1.000000)
    pub_date = models.DateTimeField('date publish')

    def __str__(self):
        return self.name_land

    def was_published_recently_for_land_model(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# Model NewConstruction
class NewConstruction(models.Model):
    name_new_construction = models.CharField(max_length=1998)
    price_new_construction = models.FloatField(5.000000)
    pub_date = models.DateTimeField('date publish')

    def __str__(self):
        return self.name_new_construction

    def was_published_recently_for_new_construction_model(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# Model Cities with relation one-to-many
class Cities(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE)
    land = models.ForeignKey(Land, on_delete=models.CASCADE)
    new_construction = models.ForeignKey(NewConstruction, on_delete=models.CASCADE)
    name_cities = models.CharField(max_length=2000)

    def __str__(self):
        return self.name_cities

www/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import House, Cities

# Create your views here.


def index(request):
    latest_house_list = House.objects.order_by('-pub_date')[:5]
    context = {'latest_house_list': latest_house_list}
    return render(request, 'www/index.html', context)


def detail(request, house_id):
    house = get_object_or_404(House, pk=house_id)
    return render(request, 'www/detail.html', {'house': house})


def results(request, house_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % house_id)


def vote(request, house_id):
    house = get_object_or_404(House, pk=house_id)
    try:
        selected_cities = house.cities_set.get(pk=request.POST['cities'])
    except (KeyError, Cities.DoesNotExist):
        return render(request, 'www/detail.html', {
            'house': house,
            'error_message': "You didn't select house",
        })
    else:
        selected_cities.cities += 1
        selected_cities.save()
        return HttpResponseRedirect(reverse('www:results', args=(house_id,)))

www/templates/www/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<form action="{% url 'www:vote' house.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ house.name_house }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{{% endif %}}
        {% for cities in house.name_cities.all %}
            <input type="radio" name="cities" id="cities {{ fofloop.counter }}" value="{{ cities.id }}">
            <label for="cities {{ fofloop.counter }}">{{ cities.cities_id }}</label><br>
        {{% endfor %}}
    </fieldset>
    <input type="submit" value="Vote">
</form>

<h1>{{ house.name_house }}</h1>
<ul>
{% for cities in house.cities_set.all %}
    <li>{{ cities.name_cities }}</li>
{% endfor %}
</ul>
</body>
</html>

www/templates/www/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django</title>
</head>
<body>
{% if latest_house_list %}
    <ul>
    {% for house in latest_house_list %}
        <li><a href="{% url 'www:detail' house.id %}">{{ house.name_house }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No house are available.</p>
{% endif %}
</body>
</html>